// int id;                          1               DbPersonReadKey                  
// int seqNo;                                       generated by us
// int amt;                         100.00          Convert to 10000
// string_t date                    01/Jan/2024     Validate and convert to YYYY-MM-DD
// string_t docNo                                   IsValidCreditCardNo (CC) Any (Doc)
// string_t receiptNo                               generated by external system